import '../../models/content_models.dart';
import 'ncert_math_g5_fractions_lesson.dart';
import 'ncert_math_g5_fractions_sections.dart';
import 'ncert_math_g5_fractions_study.dart';

final Chapter mathG5FractionsChapter = Chapter(
  id: 'ncert-g5-math-fractions',
  title: 'Fractions',
  classLevel: 'Class 5',
  board: 'NCERT',
  subject: 'Mathematics',
  unit: 'Fractions',
  mainTheme: 'Equivalent fractions, comparing fractions, fractions greater than 1, and representing fractional quantities on number lines.',
  mainIdea: 'A fraction describes a part of a whole, but the size of that part depends on the whole being divided. Two fractions can have different names but represent the same amount; these are equivalent fractions. Fractions can be compared directly when they have the same denominator or same numerator, and more generally by using useful reference fractions such as 1 and 1/2. The chapter then extends fractions beyond one whole, using parathas, pizzas and number lines to understand improper fractions and mixed numbers.',
  learningOutcomes: const [
    'Explain why fractions from different-sized wholes cannot automatically be compared.',
    'Identify and generate equivalent fractions.',
    'Compare fractions with the same denominator.',
    'Compare fractions with the same numerator.',
    'Use 1 as a reference when comparing fractions.',
    'Use 1/2 as a reference when appropriate.',
    'Recognise fractions greater than 1 and express them as mixed numbers.',
    'Represent fractions and mixed numbers on number lines.',
    'Solve real-life fraction problems involving parathas, pizzas and lengths.',
  ],
  sections: mathG5FractionsSections,
  concepts: const [
    Concept(
      id: 'c-frac-1',
      title: 'The Same-Whole Requirement',
      simpleMeaning: 'Direct comparison of fractions requires both fractions to originate from identical wholes.',
      sourceReference: SourceReference(pageNumber: 17),
    ),
    Concept(
      id: 'c-frac-2',
      title: 'Equivalent Fractions & Multiplicative Scaling',
      simpleMeaning: 'Fractions naming the same amount (1/3 = 2/6 = 3/9 = 4/12; 2/5 = 4/10 = 6/15 = 8/20) generated by multiplying/dividing by a/a.',
      sourceReference: SourceReference(pageNumber: 18),
    ),
    Concept(
      id: 'c-frac-3',
      title: 'Fraction Comparison & Reference Benchmarks',
      simpleMeaning: 'Comparing via same denominators (5/7 > 2/7), same numerators (4/5 > 4/6), benchmark 1 (7/8 < 1 < 8/6), and benchmark 1/2 (5/8 > 1/2 = 3/6).',
      sourceReference: SourceReference(pageNumber: 23),
    ),
    Concept(
      id: 'c-frac-4',
      title: 'Fractions Greater Than 1 & Mixed Numbers',
      simpleMeaning: 'When numerator > denominator, fractions exceed 1 and group into mixed numbers (5/2 = 2 1/2, 9/4 = 2 1/4, 43/4 = 10 3/4).',
      sourceReference: SourceReference(pageNumber: 24),
    ),
    Concept(
      id: 'c-frac-5',
      title: 'Number Lines & Proportional Measurement',
      simpleMeaning: 'Plotting continuous fractional distances and multiplying unit fractions for physical measurement (16 * 1/4 cm = 4 cm).',
      sourceReference: SourceReference(pageNumber: 28),
    ),
  ],
  glossary: const [
    GlossaryTerm(
      id: 'g-frac-1',
      term: 'Fraction',
      definition: 'A number representing one or more equal parts of a whole.',
      sourceReference: SourceReference(pageNumber: 17),
    ),
    GlossaryTerm(
      id: 'g-frac-2',
      term: 'Numerator',
      definition: 'The top number of a fraction showing how many equal parts are selected.',
      sourceReference: SourceReference(pageNumber: 17),
    ),
    GlossaryTerm(
      id: 'g-frac-3',
      term: 'Denominator',
      definition: 'The bottom number of a fraction showing the total equal parts making up the whole.',
      sourceReference: SourceReference(pageNumber: 17),
    ),
    GlossaryTerm(
      id: 'g-frac-4',
      term: 'Equivalent Fractions',
      definition: 'Different fractions that represent the exact same quantity or value.',
      sourceReference: SourceReference(pageNumber: 18),
    ),
    GlossaryTerm(
      id: 'g-frac-5',
      term: 'Improper Fraction',
      definition: 'A fraction where the numerator is greater than or equal to the denominator.',
      sourceReference: SourceReference(pageNumber: 24),
    ),
    GlossaryTerm(
      id: 'g-frac-6',
      term: 'Mixed Number',
      definition: 'A number made up of a whole number and a proper fraction combined (e.g. 2 1/2).',
      sourceReference: SourceReference(pageNumber: 24),
    ),
  ],
  misconceptions: const [
    Misconception(
      id: 'm-frac-1',
      label: 'Assuming 1/2 is always bigger than 1/3',
      mistake: 'Believing 1/2 is larger than 1/3 without checking if the wholes are the same.',
      correctIdea:
          '1/2 of a small whole can be smaller than 1/3 of a large whole.',
      explanation: 'Fraction sizes are relative to the dimension of the whole from which they are partitioned.',
      sourceReference: SourceReference(pageNumber: 17),
    ),
    Misconception(
      id: 'm-frac-2',
      label: 'Thinking larger denominator means larger fraction',
      mistake: 'Believing 4/6 is bigger than 4/5 because 6 is bigger than 5.',
      correctIdea: 'When numerators match, smaller denominators yield larger fractions because slices are bigger.',
      explanation: 'Dividing a whole into more parts reduces each individual part\'s size.',
      sourceReference: SourceReference(pageNumber: 23),
    ),
  ],
  visuals: const [
    Visual(
      id: 'v-frac-1',
      type: 'diagram',
      title: 'Sameer\'s Equivalent Fraction Strips (1/3 = 2/6 = 3/9 = 4/12)',
      description: 'Fraction strips showing identical shaded areas partitioned into 3, 6, 9, and 12 equal sub-divisions.',
      pageReference: 18,
    ),
    Visual(
      id: 'v-frac-2',
      type: 'chart',
      title: 'Number Line with Fractions Greater Than 1',
      description: 'Continuous number line plotting 0, 1/2, 2/2 (1), 3/2, 4/2 (2), and 5/2 (2 1/2).',
      pageReference: 28,
    ),
  ],
  teacherStudy: mathG5FractionsTeacherStudy,
  studentLesson: mathG5FractionsStudentLesson,
  practice: const [
    PracticeQuestion(
      id: 'pq-frac-1',
      questionText: 'Why are 1/3 and 2/6 called equivalent fractions?',
      difficulty: PracticeDifficulty.easy,
      cognitiveDemand: CognitiveDemand.understand,
      answer: '1/3 and 2/6 are equivalent fractions because they represent the exact same shaded amount or portion of the same whole.\nWhen a whole divided into 3 equal parts is sub-divided into 6 equal parts, 2 of the sixths cover the same area as 1 of the thirds.',
      explanation: 'Equivalent fractions name identical amounts using different equal partitions.',
      keywords: [
        'same amount of same whole',
        'same shaded area',
        '2 sixths equal 1 third',
      ],
    ),
    PracticeQuestion(
      id: 'pq-frac-2',
      questionText:
          'Explain why 4/6 is less than 4/5 even though 6 is greater than 5.',
      difficulty: PracticeDifficulty.medium,
      cognitiveDemand: CognitiveDemand.understand,
      answer: 'Both fractions have the same numerator (4 parts).\nHowever, dividing a whole into 5 equal parts creates larger individual slices than dividing the same whole into 6 equal parts (fifths are larger than sixths).\nTherefore, 4 larger fifths are greater than 4 smaller sixths (4/6 < 4/5).',
      explanation:
          'When numerators match, smaller denominators yield larger parts.',
      keywords: [
        'same numerator',
        'fifths are larger slices than sixths',
        'smaller denominator means larger parts',
      ],
    ),
    PracticeQuestion(
      id: 'pq-frac-3',
      questionText:
          'Convert the improper fractions 5/2 and 9/4 into mixed numbers.',
      difficulty: PracticeDifficulty.easy,
      cognitiveDemand: CognitiveDemand.apply,
      answer: '(a) 5/2 = 2/2 + 2/2 + 1/2 = 2 1/2.\n(b) 9/4 = 4/4 + 4/4 + 1/4 = 2 1/4.',
      explanation: 'Group full denominator sets into whole numbers.',
      keywords: ['5/2 = 2 1/2', '9/4 = 2 1/4'],
    ),
    PracticeQuestion(
      id: 'pq-frac-4',
      questionText: 'Compare: (a) 7/8 and 8/6 using 1 as a reference, (b) 5/8 and 3/6 using 1/2 as a reference, and (c) find the total length of 16 ants measuring 1/4 cm each.',
      difficulty: PracticeDifficulty.medium,
      cognitiveDemand: CognitiveDemand.apply,
      answer: '(a) 7/8 < 1 while 8/6 > 1, so 7/8 < 8/6.\n(b) 3/6 = 1/2 while 5/8 > 1/2 (since 4/8 = 1/2), so 5/8 > 3/6.\n(c) Total length = 16 * 1/4 cm = 16/4 = 4 cm.',
      explanation:
          'Apply benchmark reasoning and repeated fraction multiplication.',
      keywords: ['7/8 < 1 < 8/6', '5/8 > 1/2 = 3/6', '4 cm'],
    ),
  ],
);
